sonar.projectKey=aaronsd914_TFG
sonar.organization=aaronsd914

# Fuentes analizadas
sonar.sources=backend,frontend/src
sonar.exclusions=**/node_modules/**,**/__pycache__/**,**/*.pyc,**/migrations/**,frontend/public/**

# Python
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage-backend.xml

# JavaScript / React
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

# Codificación
sonar.sourceEncoding=UTF-8
