// test-setup.js — Se ejecuta antes de cada fichero de test
import '@testing-library/jest-dom';

// ─── Mock global de react-i18next ─────────────────────────────────────────────
// Proporciona una función t que devuelve los valores en español
const _i18nTranslations = {
  'sidebar.nav': 'Navegación principal',
  'sidebar.close': 'Cerrar menú',
  'sidebar.logout': 'Cerrar sesión',
  'sidebar.dashboard': 'Dashboard',
  'sidebar.newSale': 'Nueva venta',
  'sidebar.clients': 'Clientes',
  'sidebar.deliveryNotes': 'Albaranes',
  'sidebar.transport': 'Transporte',
  'sidebar.movements': 'Movimientos',
  'sidebar.products': 'Productos',
  'sidebar.bank': 'Banco',
  'sidebar.trends': 'Tendencias',
  'sidebar.settings': 'Configuración',
  'login.subtitle': 'Panel de gestión',
  'login.username': 'Usuario',
  'login.usernamePlaceholder': 'Nombre de usuario',
  'login.password': 'Contraseña', // NOSONAR
  'login.passwordPlaceholder': '••••••••',
  'login.showPassword': 'Mostrar contraseña',
  'login.hidePassword': 'Ocultar contraseña',
  'login.submit': 'Iniciar sesión',
  'login.submitting': 'Iniciando sesión…',
  'appearance.title': 'Apariencia',
  'appearance.darkMode': 'Modo oscuro',
  'appearance.darkModeDesc': 'Cambia entre tema claro y oscuro',
  'appearance.toggleDarkMode': 'Activar/desactivar modo oscuro',
  'appearance.colorPalette': 'Paleta de color',
  'appearance.selectPalette': 'Seleccionar paleta {{name}}',
  'appearance.language': 'Idioma',
  'appearance.languageDesc': 'Elige el idioma de la interfaz',
  'appearance.langEs': 'Español',
  'appearance.langEn': 'English',
  'appearance.selectLanguage': 'Seleccionar idioma {{lang}}',
  'common.save': 'Guardar',
  'common.saving': 'Guardando…',
  'common.cancel': 'Cancelar',
  'common.delete': 'Eliminar',
  'common.loading': 'Cargando…',
  'common.error': 'Error',
  'common.success': 'Guardado correctamente',
  'common.noResults': 'Sin resultados',
  'common.close': 'Cerrar',
  'common.filters': 'Filtros',
  'common.search': 'Buscar',
  'common.add': 'Añadir',
  'common.warning': 'Aviso',
  'common.ready': 'Listo',
  // dashboard
  'dashboard.title': 'Dashboard · Tienda',
  'dashboard.refreshing': 'Refrescando…',
  'dashboard.loadError': 'Error al cargar el dashboard',
  'dashboard.incomePeriod': 'Ingresos (mes)',
  'dashboard.expensesPeriod': 'Gastos (mes)',
  'dashboard.salesPeriod': 'Ventas del mes',
  'dashboard.warehouseOrders': 'Pedidos en almacén',
  'dashboard.warehousePending': 'Pendientes de salida',
  'dashboard.vsPrev': 'vs mes anterior',
  'dashboard.incomeExpenseChart': 'Ingresos / Gastos ({{months}} meses)',
  'dashboard.onlyIncome': 'Solo ingresos',
  'dashboard.onlyExpenses': 'Solo gastos',
  'dashboard.onlyIncomeTitle': 'Mostrar solo ingresos (vuelve a ambos si lo desactivas)',
  'dashboard.onlyExpensesTitle': 'Mostrar solo gastos (vuelve a ambos si lo desactivas)',
  'dashboard.currentMonth': 'Mes actual:',
  'dashboard.incomeUnit': 'ingresos',
  'dashboard.expensesUnit': 'gastos',
  'dashboard.dataUpTo': 'Datos hasta {{date}}',
  'dashboard.orderStatus': 'Estado de los albaranes',
  'dashboard.salesChart': 'Ventas por mes (albaranes) ({{months}} meses)',
  'dashboard.totalDeliveries': 'Total: {{count}} albaranes',
  'dashboard.recentMovements': 'Últimos movimientos',
  'dashboard.viewAllMovements': 'Ver todos los movimientos →',
  'dashboard.noMovements': 'No hay movimientos.',
  'dashboard.incomeType': 'Ingreso',
  'dashboard.expenseType': 'Gasto',
  'dashboard.warehouseSection': 'Almacén · Pendientes de salida',
  'dashboard.organizeTransport': 'Organizar transporte',
  'dashboard.noOrders': 'No hay pedidos.',
  'dashboard.colDate': 'Fecha',
  'dashboard.colType': 'Tipo',
  'dashboard.colDesc': 'Descripción',
  'dashboard.colAmount': 'Cantidad',
  'dashboard.colID': 'ID',
  'dashboard.colClient': 'Cliente',
  'dashboard.colDNI': 'DNI',
  'dashboard.colTotal': 'Total',
  'dashboard.albaranLabel': 'albarán',
  'dashboard.albaranesLabel': 'albaranes',
  'dashboard.datasetIncome': 'Ingresos',
  'dashboard.datasetExpenses': 'Gastos',
  'dashboard.datasetDeliveries': 'Albaranes',
  'dashboard.stateFianza': 'Fianza',
  'dashboard.stateAlmacen': 'Almacén',
  'dashboard.stateRuta': 'Ruta',
  'dashboard.stateEntregado': 'Entregado',
  'dashboard.months': ['Ene','Feb','Mar','Abr','May','Jun','Jul','Ago','Sep','Oct','Nov','Dic'],
  // clients
  'clients.title': 'Clientes',
  'clients.searchPlaceholder': 'Buscar por nombre, apellidos, email, DNI o teléfono…',
  'clients.loading': 'Cargando clientes…',
  'clients.noResults': 'Sin resultados',
  'clients.filtersTitle': 'Filtros',
  'clients.orderLabel': 'Orden',
  'clients.orderAsc': 'ID ascendente',
  'clients.orderDesc': 'ID descendente',
  'clients.emailDomains': 'Dominios de email',
  'clients.detailTitle': 'Detalle de cliente',
  'clients.deliveries': 'Albaranes',
  'clients.loadingLines': 'Cargando líneas…',
  // products
  'products.title': 'Productos',
  'products.loading': 'Cargando productos…',
  'products.searchPlaceholder': 'Buscar por nombre, descripción o proveedor…',
  'products.noResults': 'Sin resultados',
  'products.viewAll': 'Ver todos los productos',
  'products.groupBySupplier': 'Agrupar por proveedor',
  'products.filtersTitle': 'Filtros de productos',
  'products.supplierLabel': 'Proveedor',
  'products.allSuppliers': 'Todos los proveedores',
  'products.manage': 'Gestionar productos',
  'products.results': 'Resultados',
  'products.editing': 'Editando',
  'products.selectProduct': 'Selecciona un producto de la lista para actualizarlo o eliminarlo.',
  'products.selectSupplier': 'Selecciona proveedor',
  'products.newProduct': 'Nuevo producto',
  'products.tabList': 'Listado',
  'products.tabManage': 'Gestión',
  'products.viewAllBtn': 'Todos',
  'products.bySupplier': 'Por proveedor',
  'products.expandAll': 'Expandir todo',
  'products.collapseAll': 'Colapsar todo',
  'products.clearFilters': 'Limpiar filtros',
  'products.orderNameAZ': 'Nombre A→Z',
  'products.orderNameZA': 'Nombre Z→A',
  'products.orderPriceUp': 'Precio ↑',
  'products.orderPriceDown': 'Precio ↓',
  'products.orderSupplierAZ': 'Proveedor A→Z',
  'products.orderSupplierZA': 'Proveedor Z→A',
  'products.pageSizeLabel': 'Tamaño de página (modo "Todos")',
  'products.pageSizeDisabled': 'La paginación se aplica en el modo "Todos"',
  'products.minPriceLabel': 'Precio mínimo (€)',
  'products.maxPriceLabel': 'Precio máximo (€)',
  'products.minPricePlaceholder': 'Min €',
  'products.maxPricePlaceholder': 'Max €',
  'products.priceRangeError': 'El precio mínimo no puede ser mayor que el máximo. Corrige el rango para aplicar el filtro.',
  'products.noResultsHint': 'Prueba a quitar filtros o buscar con otro texto.',
  'products.createProduct': 'Crear producto',
  'products.supplierPrefix': 'Proveedor:',
  'products.supplierNumber': 'Proveedor #{{id}}',
  'products.noManageResults': 'No hay productos que coincidan.',
  'products.usedInAlbaranes': 'Si el producto está usado en albaranes, no se podrá borrar.',
  'products.confirmDelete': 'Confirmar eliminación',
  'products.deleteConfirmText': '¿Seguro que quieres eliminar',
  'products.thisProduct': 'este producto',
  'products.productSingular': 'producto',
  'products.productPlural': 'productos',
  'products.showingRange': 'Mostrando {{from}}–{{to}} de {{total}}',
  'products.chipSearch': 'Buscar: "{{q}}"',
  'products.chipSupplier': 'Proveedor: {{name}}',
  'products.chipOrder': 'Orden: {{label}}',
  'products.manageBtn': 'Gestionar',
  'products.show': 'Ver',
  'products.hide': 'Ocultar',
  'products.updating': 'Actualizando…',
  'products.update': 'Actualizar',
  'products.revert': 'Revertir cambios',
  'products.clean': 'Limpiar',
  'products.saving': 'Guardando…',
  'products.nameLabel': 'Nombre',
  'products.priceLabel': 'Precio',
  'products.deleting': 'Eliminando…',
  'products.filterBtn': 'Filtros',
  'products.descriptionLabel': 'Descripción',
  'products.orderLabel': 'Orden',
  'products.namePlaceholder': 'Ej: Mesa de comedor',
  'products.pricePlaceholder': 'Ej: 199.99',
  'products.descPlaceholder': 'Detalles, medidas, materiales…',
  // movements
  'movements.title': 'Movimientos',
  'movements.addMovement': 'Añadir movimiento',
  'movements.income': 'Ingreso',
  'movements.expense': 'Egreso',
  'movements.noMovements': 'No hay movimientos aún.',
  'movements.ingresosSummary': 'Ingresos',
  'movements.egresosSummary': 'Egresos',
  'movements.balanceSummary': 'Balance',
  // albaranes
  'albaranes.title': 'Albaranes',
  'albaranes.loading': 'Cargando albaranes…',
  'albaranes.noResults': 'Sin resultados',
  'albaranes.clearDates': 'Limpiar fechas',
  'albaranes.filtersTitle': 'Filtros',
  'albaranes.dateRange': 'Rango de fechas',
  'albaranes.clientDomains': 'Dominios de cliente',
  'albaranes.statusFilter': 'Estados',
  'albaranes.detailTitle': 'Detalle de albarán',
  'albaranes.linesTitle': 'Líneas',
  'albaranes.clientInfo': 'Información del cliente',
  'albaranes.stateFianza': 'Fianza',
  'albaranes.stateAlmacen': 'Almacén',
  'albaranes.stateRuta': 'Ruta',
  'albaranes.stateEntregado': 'Entregado',
  'albaranes.searchPlaceholder': 'Buscar por id, cliente, DNI o email…',
  'albaranes.dateLabel': 'Fecha:',
  'albaranes.orderLabel': 'Orden',
  'albaranes.colID': 'ID',
  'albaranes.colDate': 'Fecha',
  'albaranes.colClient': 'Cliente',
  'albaranes.colTotal': 'Total',
  'albaranes.colStatus': 'Estado',
  'albaranes.colLineId': 'ID línea',
  'albaranes.colProduct': 'Producto',
  'albaranes.colQty': 'Cantidad',
  'albaranes.colSubtotal': 'Subtotal',
  'albaranes.colName': 'Nombre',
  'albaranes.colDNI': 'DNI',
  'albaranes.colEmail': 'Email',
  'albaranes.colPhone': 'Teléfono',
  'albaranes.colCity': 'Ciudad',
  'albaranes.colDesc': 'Descripción',
  'albaranes.colUnitPrice': 'P. Unitario',
  'albaranes.clearFilters': 'Limpiar filtros',
  'albaranes.apply': 'Aplicar',
  'albaranes.totalRange': 'Rango de total (€)',
  'albaranes.rangeAvailable': 'Rango disponible: {{min}}–{{max}} €',
  'albaranes.noDomains': 'No hay dominios detectados.',
  'albaranes.tabAlbaran': 'Albarán',
  'albaranes.tabClient': 'Cliente',
  'albaranes.noLines': 'Este albarán no tiene líneas.',
  'albaranes.viewClient': 'Ver cliente →',
  'albaranes.loadError': 'No se pudieron cargar los albaranes.',
  'albaranes.loadingClient': 'Cargando cliente…',
  // newSale
  'newSale.title': 'Nueva venta',
  'newSale.clientSection': 'Cliente',
  'newSale.clientSubtitle': 'Elige un cliente existente o registra uno nuevo.',
  'newSale.useExisting': 'Usar existente',
  'newSale.productsSection': 'Productos',
  'newSale.removeItem': 'Quitar',
  'newSale.noProducts': 'No hay productos seleccionados',
  'newSale.submitBtn': 'Guardar albarán',
  'newSale.searchClientPlaceholder': 'Busca por nombre, apellidos, email o DNI…',
  'newSale.searchClientLabel': 'Buscar cliente',
  'newSale.noResults': 'Sin resultados',
  'newSale.fieldName': 'Nombre',
  'newSale.fieldSurnames': 'Apellidos',
  'newSale.fieldDNI': 'DNI',
  'newSale.fieldEmail': 'Email',
  'newSale.fieldPhone1': 'Teléfono 1',
  'newSale.fieldPhone2': 'Teléfono 2',
  'newSale.fieldStreet': 'Calle',
  'newSale.fieldNumber': 'Número',
  'newSale.fieldFloor': 'Piso/Portal',
  'newSale.fieldCity': 'Ciudad',
  'newSale.fieldPostCode': 'Código postal',
  'newSale.fieldDate': 'Fecha',
  'newSale.fieldDescription': 'Descripción',
  'newSale.placeholderName': 'Nombre',
  'newSale.placeholderSurnames': 'Apellidos',
  'newSale.placeholderEmail': 'correo@dominio.com',
  'newSale.placeholderPhone': 'Móvil',
  'newSale.placeholderPhone2': 'Otro teléfono',
  'newSale.placeholderStreet': 'Calle',
  'newSale.placeholderCity': 'Ciudad',
  'newSale.placeholderPostCode': 'CP',
  'newSale.placeholderNotes': 'Observaciones…',
  'newSale.productsSubtitle': 'Busca productos y ajusta cantidades.',
  'newSale.searchProductPlaceholder': 'Buscar producto por nombre…',
  'newSale.searchProductLabel': 'Buscar producto',
  'newSale.colProduct': 'Producto',
  'newSale.colQty': 'Cantidad',
  'newSale.colPrice': 'Precio',
  'newSale.colSubtotal': 'Subtotal',
  'newSale.noProductsHint': 'Usa el buscador para añadir productos a la venta.',
  'newSale.depositLabel': 'Registrar fianza (30% por defecto: {{amount}})',
  'newSale.depositAmount': 'Importe:',
  'newSale.depositEmpty': '(vacío = {{amount}})',
  'newSale.depositApplied': 'Aplicada: {{amount}}',
  'newSale.fieldClient': 'Cliente',
  'newSale.subtitle': 'Crea un albarán seleccionando cliente y productos.',
  'newSale.sinDNI': 'Sin DNI',
  'newSale.isRequired': '{{field}} es obligatorio',
  'newSale.totalLabel': 'Total:',
  'newSale.linesSummary': '{{lines}} línea(s) · {{items}} unidad(es)',
  'newSale.removeTitle': 'Quitar',
  // bank
  'bank.title': 'Banco',
  'bank.stripeStatus': 'Estado Stripe',
  'bank.createCharge': 'Crear cobro (Stripe Checkout)',
  'bank.recentCharges': 'Últimos cobros Stripe',
  'bank.recentChargesHint': 'Se registran al volver del pago',
  'bank.toastCancelled': 'Pago cancelado',
  'bank.toastCancelledDesc': 'El cliente canceló el pago en Stripe.',
  'bank.toastCompleted': 'Pago completado',
  'bank.toastCompletedDesc': 'Stripe confirmó el pago.',
  'bank.toastConfirming': 'Confirmando pago…',
  'bank.toastRegistered': 'Cobro registrado',
  'bank.toastAlreadyRegistered': 'Cobro ya registrado',
  'bank.toastConfirmError': 'No se pudo confirmar el pago',
  // profile
  'profile.title': 'Mi perfil',
  'profile.activeUser': 'Usuario activo',
  'profile.changeUsername': 'Cambiar nombre de usuario',
  'profile.changeUsernameHint': 'Al cambiar el nombre de usuario se cerrará la sesión y tendrás que volver a iniciarla.',
  'profile.changePassword': 'Cambiar contraseña',
  'profile.currentPassword': 'Contraseña actual',
  'profile.newUsername': 'Nuevo nombre de usuario',
  'profile.newPassword': 'Nueva contraseña',
  'profile.confirmPassword': 'Confirmar nueva contraseña',
  'profile.btnChangeUser': 'Cambiar usuario',
  'profile.btnChangePassword': 'Cambiar contraseña',
  'profile.passwordMismatch': 'Las contraseñas nuevas no coinciden',
  'profile.updateSuccess': 'Contraseña actualizada correctamente',
  // settings
  'settings.title': 'Configuración',
  'settings.accountSection': 'Mi cuenta',
  'settings.activeUser': 'Usuario activo',
  'settings.changeSessionWarning': 'Al cambiar el nombre se cerrará la sesión.',
  'settings.currentPassword': 'Contraseña actual',
  'settings.newUsername': 'Nuevo nombre de usuario',
  'settings.newPasswordFull': 'Nueva contraseña (mín. 8 caracteres)',
  'settings.confirmPassword': 'Confirmar nueva contraseña',
  'settings.btnChangeUser': 'Cambiar usuario',
  'settings.btnChangePassword': 'Cambiar contraseña',
  'settings.resumeSection': 'Resumen por email (IA)',
  'settings.resumeDesc': 'FurniGest genera automáticamente un resumen de actividad con análisis IA y lo envía al email configurado según el intervalo de días elegido.',
  'settings.emailDest': 'Email destinatario',
  'settings.startDate': 'Fecha de inicio',
  'settings.intervalDays': 'Intervalo (días)',
  'settings.sendTime': 'Hora de envío',
  'settings.nextScheduled': 'Próximos envíos programados',
  'settings.lastSent': 'Último envío: {{date}}',
  'settings.neverSent': 'Aún no se ha enviado ningún resumen',
  'settings.identitySection': 'Identidad de la tienda',
  'settings.logoLabel': 'Logo',
  'settings.logoDesc': 'Aparece en el Sidebar y en el encabezado del PDF de albaranes. PNG/JPG, máx. 4 MB.',
  'settings.removeLogo': 'Eliminar',
  'settings.noLogo': 'Sin logo',
  'settings.changeLogo': 'Cambiar logo',
  'settings.uploadLogo': 'Subir logo',
  'settings.emailSignature': 'Firma en emails de albarán',
  'settings.emailSignatureDesc': 'Texto que aparece al final de los emails enviados al entregar un albarán.',
  'settings.saveSignature': 'Guardar firma',
  // trends
  'trends.title': 'Tendencias',
  'trends.comparePrev': 'Comparar periodo anterior',
  'trends.exportAnalysis': 'Exportar análisis',
  'trends.exportWithComparison': 'Exportar + comparativa',
  'trends.kpiIncome': 'Ingresos',
  'trends.kpiOrders': 'Pedidos',
  'trends.kpiAOV': 'AOV',
  'trends.kpiAvgSpend': 'Gasto medio/cliente',
  'trends.comparison': 'Comparativa',
  'trends.colMetric': 'Métrica',
  'trends.colCurrent': 'Actual',
  'trends.colPrev': 'Anterior',
  'trends.aiReading': 'Lectura IA',
  'trends.topProducts': 'Top productos',
  'trends.colProduct': 'Producto',
  'trends.colUnits': 'Unidades',
  'trends.colRevenue': 'Facturación',
  'trends.aiReport': 'Informe IA',
  'trends.aiAssistant': 'Asistente IA',
  'trends.resetConversation': 'Reiniciar conversación',
  'trends.chip1': 'Producto que más crece',
  'trends.chip2': 'Detectar picos',
  'trends.chip3': 'Subir AOV',
  'trends.chatPlaceholder': 'Pregunta sobre ventas, productos…',
  'trends.aiGreeting': 'Hola 👋. Puedes preguntarme por ventas, productos, clientes, comparativas por fechas, o lo que necesites.',
  // transport
  'transport.title': 'Transporte',
  'transport.search': 'Buscar',
  'transport.warehouse': 'Almacén',
  'transport.inRoutePending': 'En ruta (pendiente camión)',
  'transport.trucks': 'Camiones',
  'transport.addTruck': 'Añadir camión',
  'transport.list': 'Listado',
  'transport.dragHandle': 'Arrastra para mover',
  'transport.loading': 'Cargando…',
  'transport.tabWarehouse': 'Almacén ({{n}})',
  'transport.tabInRoute': 'En ruta ({{n}})',
  'transport.flowHint': 'Flujo recomendado:',
  'transport.flowRoute': 'Almacén → En ruta → Camión',
  'transport.ordersCount': '{{n}} pedidos',
  'transport.noPedidos': 'Sin pedidos.',
  'transport.nothingToAssign': 'Nada por asignar.',
  'transport.toRouteBtn': 'En ruta',
  'transport.delivered': 'Entregado',
  'transport.truckLabel': 'Camión {{id}}',
  'transport.acceptRoute': 'Aceptar ruta',
  'transport.removeBtn': 'Quitar',
  'transport.invoiceTitle': 'Registrar gasto (7%) y descargar factura',
  'transport.noAlbaranes': 'No hay albaranes en este camión',
  'transport.deleteTruckTitle': 'Eliminar camión (solo si está vacío)',
  'transport.emptyTruckFirst': 'Vacía el camión para eliminarlo',
  'transport.dropHere': 'Arrastra aquí para asignar.',
  'transport.noTrucks': 'No hay camiones aún.',
  'transport.accepted': 'Aceptada',
  'transport.emptyBadge': 'Vacío',
  'transport.closeBtn': 'Cerrar',
  'transport.deleteBtn': 'Eliminar',
  'transport.addBtn': 'Añadir',
  'transport.cannotDelete': 'No se puede eliminar',
  'transport.emptyTruckHint': 'Vacía el camión para poder eliminarlo.',
  'transport.truckNote': 'Los camiones que aparezcan en rutas también se guardan, para que no desaparezcan cuando queden vacíos.',
  'transport.moveToRoute': 'Pasa el pedido a EN RUTA (pendiente de camión)',
  'transport.searchPlaceholder': 'ID, cliente, total o fecha…',
};

function _t(key, opts = {}) {
  let val = _i18nTranslations[key] ?? key;
  if (opts?.returnObjects) return val;
  if (opts && typeof opts === 'object' && typeof val === 'string') {
    val = val.replace(/\{\{(\w+)\}\}/g, (_, k) => opts[k] ?? k);
  }
  return val;
}

vi.mock('react-i18next', () => ({
  useTranslation: () => ({
    t: _t,
    i18n: { language: 'es', changeLanguage: vi.fn() },
  }),
  initReactI18next: { type: '3rdParty', init: vi.fn() },
  Trans: ({ i18nKey }) => i18nKey,
}));

// Silencia errores de ResizeObserver que lanzan chart.js en jsdom
globalThis.ResizeObserver = class ResizeObserver {
  observe() {}
  unobserve() {}
  disconnect() {}
};

// Mock global de fetch para evitar llamadas reales a la API en tests
globalThis.fetch = vi.fn(() =>
  Promise.resolve({
    ok: true,
    json: () => Promise.resolve([]),
  })
);
